### PR TITLE
Implemented mathematical cossim function, and inconsistent result issue resolved (see PR description)

### PR DESCRIPTION
**Pull request by pmirski**
**Inconsistent result issue:** 
Sometimes the same query title results in different suggested STG

**Why I left it as is:**
When the input LTG title has 0 cossim score with all LTG titles it's compared against, it seems that an LTG title is selected as the most similar "at random" (random in the sense that I don't know how it choose, but it chooses one).

The same is true when the input LTG title has 0 cossim score for all STGs it's compared against.

I am content with leaving it as is. We can get consistency by for example checking if all scores are 0, then picking the first alphabetical one, but I don't think that's needed for our functionality? Moreover, it still won't be consistent, since the 50 LTGs being compared changes every couple of minutes (when the cache list of LTGs is against refreshed using random sampling from database).

### CODE REVIEW

**Comment by jeremywiens** [comment]
So when is "No suggested goal found" returned?

Also, are results always consistent if a long-term goal with a word match to a given title always consistent?

ie if the cache has long term goals: ("get healthy", "don't  do drugs") and the title given is ("do healthy drugs"), will the result always be the same?

What about the simpler case 

If the cache has long term goals: ("get healthy", "become a guitar player") and the title given is ("practice guitar"), will the result always be the same? In the app I sometimes get a result in this case and other times I would get "No suggested goal found"

**Comment by pmirski** [comment]
> So when is "No suggested goal found" returned?
Only returned if there is no LTG with a STG in the database cache, where the LTG title and at least 1 STG title both have at least one character.

Back end on VM may currently behave differently. I made a few changes (more than this PR) that may affect. Maybe best to merge this PR, then pull on the back end, then I test backend?

> Also, are results always consistent if a long-term goal with a word match to a given title always consistent?
> 
> ie if the cache has long term goals: ("get healthy", "don't do drugs") and the title given is ("do healthy drugs"), will the result always be the same?
No (according to my local testing of code version in this PR). Because 2 cossim comparisons occur:
1. Between query LTG title and all LTG titles in cache, then
2. Between query LTG title and all valid (i.e. has at least 1 character) STG titles
In your example, it will always examine the STGs of "don't do drugs". But if the cossim score  is the same between query-LTG and all STG titles of "don't do drugs", you'll get a "random" choice from these STGs.

> What about the simpler case
> 
> If the cache has long term goals: ("get healthy", "become a guitar player") and the title given is ("practice guitar"), will the result always be the same? 
No, for the same reason as above answer (i.e. LTG "become a guitar player" will always be chosen, may return different one of its STGs).

> In the app I sometimes get a result in this case and other times I would get "No suggested goal found"
I believe a few things have changed since last pull on the back-end that may have gotten rid of this. I would suggest my merging, and then I'll test the back end using Insomnia (i.e. test REST calls), and then can test with whichever .apk you think is best.

2 notes on this last issue:
#1: I'm also realizing that maybe we should have agreed to always pull from back-end whenever back-end PR was merged (In fact, that may have been agreed on and I missed it)
#2: If I click *rapidly* with my mouse to make a GET call with the same input, approximately 1 in every 100 API calls (no exaggeration) I see I received "No suggested goal found". Honestly not sure how to test for that, or if we need to?

**Comment by yaoharry** [comment]
> 
> Back end on VM may currently behave differently. I made a few changes (more than this PR) that may affect. Maybe best to merge this PR, then pull on the back end, then I test backend?
> 

To make it easier to test with the server database without deploying the code to the server, you can replace the url string in src/db/database.js with the server IP instead of localhost.

**Comment by pmirski** [comment]
> > Back end on VM may currently behave differently. I made a few changes (more than this PR) that may affect. Maybe best to merge this PR, then pull on the back end, then I test backend?
> 
> To make it easier to test with the server database without deploying the code to the server, you can replace the url string in src/db/database.js with the server IP instead of localhost.

Ah. Nice. Good to know.

Thinking about it, I guess it should actually make no difference as to whether testing locally or on back-end. Rn, the issue is testing integration (i.e. testing as Jeremy has, from FE, to see if it's a FE issue). Since it behaves as I described now, I should run Jeremy's stated test on it using an .apk, and then confirm or update this PR.

I think we should decide on an .apk file for everyone to do their own integration tests with, and update that periodically (with an announcement). 
(if something like this has been agreed, sorry, i forgot! :) )

**Comment by yaoharry** [comment]
> > > Back end on VM may currently behave differently. I made a few changes (more than this PR) that may affect. Maybe best to merge this PR, then pull on the back end, then I test backend?
> > 
> > 
> > To make it easier to test with the server database without deploying the code to the server, you can replace the url string in src/db/database.js with the server IP instead of localhost.
> 
> Ah. Nice. Good to know.
> 
> Thinking about it, I guess it should actually make no difference as to whether testing locally or on back-end. Rn, the issue is testing integration (i.e. testing as Jeremy has, from FE, to see if it's a FE issue). Since it behaves as I described now, I should run Jeremy's stated test on it using an .apk, and then confirm or update this PR.
> 
> I think we should decide on an .apk file for everyone to do their own integration tests with, and update that periodically (with an announcement).
> (if something like this has been agreed, sorry, i forgot! :) )

Yeah, if everything works fine on the APK then I'm fine with cosine similarity as it is.

**Pull request merged**
