### PR TITLE
added alerts when users level up or achieve award

### PR DESCRIPTION
**Pull request by n-lina**

### CODE REVIEW

**Comment by jeremywiens** [comment]
I think the alters will cause the detox tests to fail, could you check that?

**Comment by n-lina** [comment]
the alert only happens when users level up or get an award; is this expected to happen in any of your tests?

**Comment by jeremywiens** [comment]
Yes, are you able to run detox test?

**Comment by jeremywiens** [comment]
How about we just use a toastr? This would be less obtrusive for the user.

https://www.npmjs.com/package/react-native-toast-message

**Comment by n-lina** [comment]
toaster is great idea

**Pull request merged**
